### ISSUE TITLE
Access HYR SENSE 2024 Application/Env

### ISSUE THREAD

**Issue by amfriesz** [CU-ESIIL/HYR-SENSE#1]
Access to HYR SENSE 2024 Application

- [x] @amfriesz 
- [x] @mjami00 
- [x] @ayialind 
- [x] @eculler 
- [x] @serbinsh 

Please add others

**Comment by amfriesz** [comment]
Hey @Ckster, I'm still unable to access the HYR SENCE 2024. I have not seen an invite email in my inbox or junk.

**Comment by Ckster** [comment]
Try looking under 'Shared with me' from the discovery environment apps page. I just added everyone to the workshop - so all should have access.

**Comment by amfriesz** [comment]
I'm able to access the application now.

**Comment by mjami00** [comment]
I am able to access Cyverse and access HYRE SENSE 2024.
