### ISSUE TITLE
Remove default python kernel on the HYR-SENSE image

### ISSUE THREAD

**Issue by eculler** [CU-ESIIL/HYR-SENSE#10]
Make sure that the first choice for jupyter kernels is the hyr-sense environment.

**Comment by serbinsh** [comment]
We want to have to avoid having to open a new notebook and then select the HYR-SENSE kernel. e.g. 

<img width="2073" alt="Screenshot 2024-03-20 at 3 52 41 PM" src="https://github.com/CU-ESIIL/HYR-SENSE/assets/3067369/b9dc7961-ad13-45bd-a856-aec5d2b91215">
