### ISSUE TITLE
CyVerse issues

### ISSUE THREAD

**Issue by serbinsh** [CU-ESIIL/HYR-SENSE#17]
I'm not sure where to report these issues I am finding as I am working through tutorials for the workshop but for now to keep track and make these visible to all, I will use this issue.

First, following the instructions for cloning repos, I noticed that the instructions and the clone tool both download via HTTPs however then demonstrate/show to register SSH keys.  This requires the extra step of updating your repo remotes in your local clone so that you can actually push changes to the repo. This is done through the instructions and notebook example, which i have placed a copy in the repo folder.  In other words, the clone button works for just downloading but more clunky to download to then make edits that you want to commit because of the need to add an SSH url to remotes then register keys etc

I am also struggling to figure out how to not close my active analysis sessions but maintain persistent storage.  I thought as long as I didnt terminate bit shutdown my active notebook session (i.e. the analysis session is still running but I closed the window).  However, even if its still running when I re-open the analysis my work is gone. This is making it hard to develop outside of a single period of time - that is if I am coming back to work I ahve to re-establish my git repo and SSH keys to keep working and have to be sure to commit my branch otherwise my work is lost. Again even if I dont terminate

Also we are still missing one library for hdf5 support in xarray which we need for emit and ecostress. Note the fix listed here: https://github.com/CU-ESIIL/HYR-SENSE/issues/14

**Comment by serbinsh** [comment]
CC @Ckster @CibeleAmaral

We definitely want to be clear with attendees how they can keep their work secure during the workshop between workshop days (and even right after) but also for our dev efforts, it would be good to know how we can keep what we are working on even if we have to step away for a few hours to a day

**Comment by serbinsh** [comment]
OK - I just figured out that to keep persistent storage you need to "log out" not "shutdown".  If you shut down, even if you dont terminate the analysis, you will loose your data.  

Moving forward I will make sure to logout and _not_ shut down

**Comment by Ckster** [comment]
Hi Shawn,

Another option for persistent storage is having users back things up to the data-store. At our next meeting I will go over this and also show some potential drawbacks of mounting the data-store to the containers.

**Comment by serbinsh** [comment]
OK - thanks @Ckster! That would be helpful.  I am slowly figuring out an optimal workflow for notebook dev, at least for myself

Luckily getting better at finding EMIT scenes at least

**Comment by amfriesz** [comment]
This is great information to know. Thanks for identifying these things @serbinsh!

**Comment by serbinsh** [comment]
Fixed
