### ISSUE TITLE
Create agriculture - food sovereignty notebook

### ISSUE THREAD

**Issue by ayialind** [CU-ESIIL/HYR-SENSE#2]
Supporting agricultural efforts and food sovereignty through identifying applications of EMIT and ECOSTRESS data for crop and native vegetation health mapping
- [x] need to identify small farms/Boulder County public data 
- [x] NASS data? / cropland data layer?
- [x] Shapefiles/GIS data on git associated with demo (Colorado ag)
- [x] Generate Code
- [x] Publish to Cyverse/Github

-

**Comment by serbinsh** [comment]
Max and Shawn to lead with help from others

**Comment by serbinsh** [comment]
Relevant other datasets

https://datagateway.nrcs.usda.gov/

Cropland Data Layer
https://croplandcros.scinet.usda.gov/
https://www.nass.usda.gov/Research_and_Science/Cropland/Release/index.php

Colorado GIS
https://cdss.colorado.gov/gis-data/gis-data-by-category
https://www.coloradoview.org/colorado-gis/

For other states, e.g. California
https://data.cnra.ca.gov/dataset/statewide-crop-mapping

**Comment by serbinsh** [comment]
List of possible EMIT scenes found through and EarthData search

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20240412T210505_2410314_026/EMIT_L2A_RFL_001_20240412T210505_2410314_026.nc

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20240404T174917_2409512_019/EMIT_L2A_RFL_001_20240404T174917_2409512_019.nc

https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20230729T205630_2321014_019/EMIT_L2A_RFL_001_20230729T205630_2321014_019.nc


https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20230822T175130_2323412_008/EMIT_L2A_RFL_001_20230822T175130_2323412_008.nc


Example search params (remember to keep scrolling!)
![Screenshot 2024-04-16 at 8 23 01 AM](https://github.com/CU-ESIIL/HYR-SENSE/assets/3067369/d4b6f333-7a09-464d-b4c3-ad5978bc3a9a)

**Comment by serbinsh** [comment]
Notebooks have been generated.  closing
